### PR TITLE
[fixed] Remove arrow function from ES5 source

### LINKED ISSUE #268: Unexpected token: punc ()) on builds with 1.6.0
### Summary:
Getting build failures when pointing at `1.6.0` due to `SyntaxError: Unexpected token: punc ()) [.../react-modal/lib/components/Modal.js:56,0]`

### PR DESCRIPTION
**Pull request by claydiffrient**
Fixes #268

Changes proposed:
- Remove arrow function

Upgrade Path (for changed or removed APIs):
- N/A

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by rpechayr** [comment]
I think it is worth unpublishing 1.6.0 and republishing with the fix. No one ever needs to use the current 1.6.0 instead of this one.

**Comment by claydiffrient** [comment]
@rpechayr I agree with the sentiment, but my understanding from https://docs.npmjs.com/cli/unpublish is that I can't do that.

> Even if a package version is unpublished, that specific name and version combination can never be reused. In order to publish the package again, a new version number must be used.

So I'll likely just deprecate 1.6.0 and publish 1.6.1.

**Comment by rpechayr** [comment]
Good for me :), as long as the problem quickly disappears for all of us

**Comment by selvagsz** [comment]
Can we get this merged soon please ?

**Comment by pluddy** [comment]
@claydiffrient all good here

**Pull request merged**
