### PR TITLE
[added] Propagate event on close request

### PR DESCRIPTION
**Pull request by robertklep**
As requested in #69

### CODE REVIEW

**Comment by robertklep** [comment]
*bump*

**Comment by xiaokekeT** [comment]
yeah I need it

**Comment by claydiffrient** [comment]
@robertklep If you could resolve any conflicts and add a spec for this, I'm happy to merge it.

**Comment by robertklep** [comment]
@claydiffrient done 😀

**Comment by diasbruno** [comment]
@robertklep this is really great. +1

**Comment by claydiffrient** [comment]
@robertklep Sorry to not have merged this yet.  It appears there are conflicts again.  Mind fixing and I'll merge as soon as possible to avoid more.

**Comment by robertklep** [comment]
@claydiffrient should merge cleanly now 👍🏼

**Comment by diasbruno** [comment]
👍🏼

**Pull request merged**
