### PR TITLE
[fixed] Regenerate package-lock.json to fix event-stream-3.3.6 issue

### PR DESCRIPTION
**Pull request by jitinmaher**
Fixes [#[721]](https://github.com/reactjs/react-modal/issues/721).

**Changes proposed:**
This PR regenerates package-lock.json which fixes event-stream-3.3.6 issue caused because of the [recent security incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)

**Acceptance Checklist:**
- [ ] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [ ] Documentation (README.md) and examples have been updated as needed.
- [ ] If this is a code change, a spec testing the functionality has been added.
- [ ] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
Thank @jitinmaher. I'll have a look on this PR later.

**Comment by jitinmaher** [comment]
Thanks @diasbruno . I wanted to fix this issue because its failing the build and **blocking** other PR( https://github.com/reactjs/react-modal/pull/720 ) merges.

**Comment by diasbruno** [comment]
Maybe you can include this on the other PR.

**Comment by jitinmaher** [comment]
Sure, will do it.

**Comment by jitinmaher** [comment]
Hey @diasbruno , I have updated https://github.com/reactjs/react-modal/pull/720 with this fix. Builds and test cases are passing in the PR now. I think we can merge it.

**Comment by diasbruno** [comment]
Great. So, I'll close this PR in favour of #720.

**Pull request closed without merging**
