### PR TITLE
Updated eslint and a few related deps

### PR DESCRIPTION
**Pull request by adityavohra7**
Updated `eslint` and some related deps. I then ran `yarn lint` and manually fixed some errors.

Acceptance Checklist:
- [DONE] All commits have been squashed to one.
- [DONE] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [N/A] Documentation (README.md) and examples have been updated as needed.
- [N/A] If this is a code change, a spec testing the functionality has been added.
- [N/A] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by adityavohra7** [comment]
Woops, I'll rebase on master and update the PR.

**Comment by diasbruno** [comment]
Ah, can you add `[chore]` on the message commit, please?

**Comment by adityavohra7** [comment]
Updated! Haha much simpler diff now 😅

**Comment by adityavohra7** [comment]
@diasbruno, would you be open to another PR adding [`prettier`](https://github.com/prettier/prettier) for auto-formatting of JS?

**Comment by diasbruno** [comment]
Of course. I'm here to help. I'm following the [reactcommunity guide](https://reactcommunity.org) and trying to help with this library. :)

Please go ahead and I'll help with code review.

**Comment by diasbruno** [comment]
I was busy this days, but I'll get this merged today.

**Pull request merged**
