### PR TITLE
[fixed] clear the delayed close timer when modal opens again.

### PR DESCRIPTION
**Pull request by diasbruno**
Continuation of the fix #134. Look at this PR (#134) for more information.

- added spec to validate the fix.
- commits were not squashed to preserve the commit made by @CompuIves.

Thanks, @CompuIves.

### CODE REVIEW

**Comment by CompuIves** [comment]
Thanks a lot for writing a test for it! Hopefully we can merge this soon :shipit:.

**Comment by diasbruno** [comment]
@claydiffrient can you have a look in this PR?

**Comment by claydiffrient** [comment]
Looks good merging now

**Comment by claydiffrient** [comment]
Released in v1.4.0

**Pull request merged**
