### PR TITLE
[added] refresh portalClassName on componentWillUpdate

### PR DESCRIPTION
**Pull request by LuSimeon**
Changes proposed:
- Allow to change portalClassName on component update

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
@LuSimeon Can you add a test case? :)

**Comment by jandramila** [comment]
What is the status of this? I´m in the need of this enhancement, @LuSimeon do you need any help to write the test case?

**Comment by LuSimeon** [comment]
@jandramila I'm not sure with the utility of this PR, I realized that I had a bad use of React when I tried to add a test case. The portalClassName already refresh on component's state change. What is the issue your facing to ?

**Comment by LuSimeon** [comment]
@diasbruno I've finally succeed to add a test case, can you check these ?

**Comment by LuSimeon** [comment]
Hi, what is the status of this ? Is there someone to review this PR ?

**Comment by diasbruno** [comment]
@LuSimeon I'll pushed this PR to version `1.8`. I'll test it again after `1.7` is close.

**Comment by diasbruno** [comment]
@LuSimeon Got you patch on `v1.9.5`. Sorry for taking so long to merge.
You patch is 3139e85. I just did a rebase.
Thank you.

**Pull request closed without merging**
