### PR TITLE
[fixed] when ModalPortal is clicked, shouldClose is true if shouldClo…

### LINKED ISSUE #590: Modal opened by using mouse right click was not closed even if I clicked ModalPortal.
React-modal is not closed at first click on Linux.
If Modal is opened by mouse right click like a contextmenu, the modal is closed by twice clicking.
A modal that I opened as mouse left click is normal.
And the strange situation is broken only on  **_Linux_**.

### Steps to reproduce:
 1. click the button using mouse right click.
 2. click a background using mouse left click. The modal is not closed.
 3. click a background using mouse left click again. Then the modal is closed.

### Expected behavior:
 I need to close it at once although I opened a modal using mouse right click.

### Link to example of issue:
[this is sample code](https://codepen.io/jongkeun/pen/PEQqbY)

### Additional notes:
Thank you for your project.

### PR DESCRIPTION
**Pull request by Jongkeun**
- Fixes #590.

Changes proposed:
- To close it at once on Linux although I opened a modal using mouse right click.

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
Thanks, @Jongkeun. This seems ok. I'll run some tests and if everything is fine, we merge this.

**Comment by diasbruno** [comment]
Thanks, @Jongkeun!!

**Comment by Jongkeun** [comment]
I'm so glad you thanked me.
I will try to help later too, if I can.
So happy to be a contributor!
Thanks! @diasbruno .

**Comment by diasbruno** [comment]
Release `v3.1.11`.

**Pull request merged**
