### PR TITLE
[fixed] strict matching for tabbable nodes

### LINKED ISSUE #1014: Focus trap incorrectly finds tabbable elements
### Summary:
The regex to determine focusable elements is not specific enough.

https://github.com/reactjs/react-modal/blob/v3.16.1/src/helpers/tabbable.js#L16
```
const tabbableNode = /input|select|textarea|button|object|iframe/;
```

In the world of web-components, it is very common to have these names be used in the element tag. Say I have an internal library or a library pulled from the community that is solely build with web-components. Unlike react, the web-component name shows as part of the DOM Tree.
```
<awesome-button>
  <button ...></button>
</awesome-button>

<awesome-input-field>
  <input ... />
</awesome-input-field>
```

The regex is matching both `<awesome-button>` and `<button>` as focusable. With this, the `head` and `tail` checks don't work correctly.
https://github.com/reactjs/react-modal/blob/v3.16.1/src/helpers/scopeTab.js#L32-L38

### Steps to reproduce:

Created a codepen https://codepen.io/bouncehead13/pen/WNabvGY where focus does not stay trap.

The general problem is all with the regex matcher being too broad with its checks.
 1. `/input|select|textarea|button|object|iframe/.test('button')` -- GOOD
 2. `/input|select|textarea|button|object|iframe/.test('awesome-button')` -- Should not match, but does
 3. `/input|select|textarea|button|object|iframe/.test('input')` -- GOOD
 4. `/input|select|textarea|button|object|iframe/.test('awesome-input-field')` -- Should not match, but does

### Expected behavior:
Only true focusable nodes are allowed.

### Proposed solution:
Instead of the regex checking as 'contains', change it to enforce 'full word' matches
```
// bad, checks nodeName is anywhere
const tabbableNode = /input|select|textarea|button|object|iframe/;

// good, matches whole nodeName `/^(...)$/`
const tabbableNode = /^(input|select|textarea|button|object|iframe)$/;
```

### PR DESCRIPTION
**Pull request by bouncehead13**
Fixes #1014.

Changes proposed:
- Make node name matcher more strict to search whole word, not partial
- Added example with a web component

Acceptance Checklist:
- [X] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [X] Documentation (README.md) and examples have been updated as needed.
- [X] If this is a code change, a spec testing the functionality has been added.
- [ ] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by bouncehead13** [comment]
@diasbruno Following up to see if we could move this forward and start gathering feedback.

**Comment by diasbruno** [comment]
@bouncehead13 Can you rebase your PR please? I've fixed the action issue.

**Comment by bouncehead13** [comment]
@diasbruno all set. Updated to the latest with GH Action changes.

**Review by diasbruno — APPROVED** [review]

**Comment by bouncehead13** [comment]
@diasbruno Is there anything remaining I can help with to move this forward?

**Comment by bouncehead13** [comment]
@diasbruno More of my teams are facing this problem breaking accessibility. It would be great to have this merged in with a new release. Thanks!

**Comment by doeg** [comment]
Hey @diasbruno! :) I wanted to see if there's anything I can do to be helpful to get this one merged. 🙇

**Comment by diasbruno** [comment]
Thanks, @doeg. I'll make a release later.

**Comment by diasbruno** [comment]
Also, thanks @bouncehead13. For taking the time to work on this, and, I'm sorry it took so long to merge.

**Pull request merged**
