### PR TITLE
[added] Added an id prop, applied to the modal dialog (content)

### LINKED ISSUE #763: Is it possible to pass an 'id' prop?
Can we pass an id prop to the main modal component? If not is this something the developers would consider? I could submit a PR if so.

Thanks

### PR DESCRIPTION
**Pull request by YassienW**
Fixes #763 

Changes proposed:

- Adding an 'id' prop to be passed to the dialog component

Acceptance Checklist:
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x]  Documentation (README.md) and examples have been updated as needed.

### CODE REVIEW

**Comment by diasbruno** [comment]
Hi @YassienW, it all looks good...can you add a test case for this, please?

**Comment by YassienW** [comment]
Done

**Comment by diasbruno** [comment]
Thanks, @YassienW.

**Comment by diasbruno** [comment]
Released `3.9.1`.

**Comment by YassienW** [comment]
Thank you for the quick release

**Pull request merged**
