### PR TITLE
Update `warning` to v4

### PR DESCRIPTION
**Pull request by michaltk**

### CODE REVIEW

**Comment by diasbruno** [comment]
Thanks for the PR, @michaltk!

**Comment by michaltk** [comment]
Thanks!
Any chance of this getting published?

**Comment by diasbruno** [comment]
I'll do my best to make a release ASAP.

**Comment by michaltk** [comment]
Thank you!

**Comment by diasbruno** [comment]
Released `3.8.2`. 
Thanks for updating this lib.

**Pull request merged**
