### PR TITLE
[added] module for default style

### PR DESCRIPTION
**Pull request by tyrsius**
This new module allows `defaultStyles` to be overridden globally.
Test verifies that changed styles are used by the modal

### CODE REVIEW

**Comment by tyrsius** [comment]
This doesn't actually work, since the built version of the library only exports the Modal component. This needs some more thought

**Comment by claydiffrient** [comment]
Yeah, I was wondering how it would actually get the styles out there for use.  Otherwise, it looks like a good PR.

My thinking is maybe expose them via a `Modal.defaultStyles` or similar.

**Comment by tyrsius** [comment]
I will do that. I've been working with ES6 too much lately and forgot named exports aren't a real thing in npm-land

**Comment by tyrsius** [comment]
@claydiffrient ok, that should do it. I updated the README this time, too

**Comment by claydiffrient** [comment]
Cool cool... I'm busy on other stuff right now, so I can't review it properly right now.  I'll look into it tonight and merge before I cut the next release.

**Pull request merged**
