### PR TITLE
[fixed] forward onKeyDown and onClick events.

### LINKED ISSUE #184: Cannot respond to keypress events on the modal content
### Summary:

After the modal is open, focus is given to the modal content element, which is an element that is created by react-modal. When any key press is made on this element, it is not propagated to the child, so there is no way for anyone to define keypress events on the modal.
### Steps to reproduce:
1. Use demo modal, with content wrapped in parent div with onKeyPress handler.
2. Render, and try to fire keypress event.
3. Nothing happens.
### Expected behavior:

Keypress should be propagated down to the children - especially in the case that there is only one child, which is the parent of the rest of the content. Alternatively, Modal component should accept onKeyPress handler which is called if whatever keypress handler is on `.ReactModal__Content` element is not triggered (esc seems to be the only key that it's watching for). The latter seems easier to implement and more useful.
Eg left/right in image carousel.

### PR DESCRIPTION
**Pull request by diasbruno**
Forward onKeyDown and onClick events.

Fixes #184.

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
It should not be necessary to forward this events. Just use a `<div />` wrapping the modal content.

**Comment by kendallb** [comment]
Is this actually fixed? I am trying to attach a key handler and the only way I can do it is to wrap the modal in my own div and attach the handler to that, but that is not a clean solution. I tried adding an onKeyDown handler to the modal itself, but that did not do anything? Suggestions?

**Comment by diasbruno** [comment]
Hi @kendallb, the idea is to separate the keyboard/mouse events from the modal and the component that goes in the modal.

**Comment by kendallb** [comment]
Well that was my original approach as well but that does not work in all situations because it is outside the modal block so it stays in the DOM where you use the component rather than moving to the end of the DOM like the modal block does.

It would be a lot better if it would forward events onto my event handler for me.

**Comment by diasbruno** [comment]
It's a trade off to keep the separation between components. Of course, we can review this approach and implement the forward method. 
You can have a look on issue #184 for further information.

**Comment by kendallb** [comment]
That one is closed also and I did implement the solution fritz mentioned and it works. It’s just not a logical solution so if someone else runs across the problem without finding the ticket they won’t figure it out. My initial assumption was I could just register key down with the modal and it would work, and it did not. If that worked, most people would figure that out quickly. Probably the same goes for mouse events.

**Comment by diasbruno** [comment]
Good point. I'll have a look on some options to either merge this PR or update the documentation explaining why react-modal don't allow to hook on input events.

**Comment by diasbruno** [comment]
Thanks for the ideas.

**Comment by kendallb** [comment]
Thanks for the module! Apart from these minor issues it works great. Took me a bit to pull the styles I used to use for jQuery UI to work with my react dialogs, but once I got it working it works really well.

**Pull request closed without merging**
