### PR TITLE
Move API documentation from README to gitbook

### LINKED ISSUE #454: Move documentation from README.md to gitbook.
Currently, `react-modal` has 2 documentations: [README.md](https://github.com/reactjs/react-modal/blob/master/README.md) and [gitbook](https://reactjs.github.io/react-modal).

Perhaps we can shrink the `README.md` and redirect to `gitbook` when someone needs to read the full api of react-modal. This way, we just need to update the documentation in one place.

The new readme can have this sections:

- Banner (about + docs link)
- Installation
- Example (copy & paste)
- Demo
- License

### PR DESCRIPTION
**Pull request by ianprime0509**
Fixes #454.

This is a follow-up to PR #612; I took all the information from the README that wasn't already in the book and put it there, and then I replaced the API information in the README with a link to the book.  Let me know if there's any extra information you think is still missing from the book, and I'll add it!

Changes proposed:
- Remove duplicate information in README.md in favor of gitbook reference.
- Move remaining additional API details from README.md into gitbook.

Upgrade Path (for changed or removed APIs): N/A

Acceptance Checklist:
- [X] All commits have been squashed to one.
- [X] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [X] Documentation (README.md) and examples have been updated as needed.
- [X] If this is a code change, a spec testing the functionality has been added.
- [X] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
Fantastic! Thank you again, @ianprime0509!

**Comment by diasbruno** [comment]
I'll release the new version of the docs after merging this one.

**Comment by ianprime0509** [comment]
No problem, happy to help!

**Comment by diasbruno** [comment]
Can you add `[chore]` to the commit message, please? I'm reviewing #588 right now, so we can release the docs and this new feature for `v3.3.1`.

**Comment by ianprime0509** [comment]
Yes; I amended the commit accordingly.

**Comment by diasbruno** [comment]
Thanks!!

**Comment by diasbruno** [comment]
There is one place missing update (Table of Contents).

**Comment by ianprime0509** [comment]
Oh, my bad!  I'll fix it and send in another (small) PR for it.

**Pull request merged**
