### PR TITLE
[fixed] Ensure after-open css transitions work in Safari 14 & Mobile Safari

### LINKED ISSUE #846: after-open CSS transitions fail in Safari 14 & mobile Safari
### Steps to reproduce:

 1. Open any modal with a defined CSS transition in Chrome or Safari <14 (`after-open` transition works)
 2. Open any modal with a defined CSS transition in Safari 14 or mobile Safari (`after-open` transition fails)

### Expected behavior:
Transitions should always work when defined correctly no matter what browser is being used

### Link to example of issue:
Existing (broken): https://codesandbox.io/s/heuristic-jennings-8c54r (works in Chrome and old Safari browsers, but NOT in Safari 14+ or mobile Safari)
"Fixed" (using `onAfterOpen with special consumer-defined `show-open` class): https://codesandbox.io/s/safari-14-bug-experimental-zlzdl

### Additional notes:
It struck me that perhaps the issue was that when the modal is mounted, it is immediately mounted with the open state and initially renders with the after-open class. It's actually kind of surprising, then that Chrome shows a transition, when technically nothing is really changing. Perhaps the old browser interpreter is inferring developer intent or doing something wrong. ¯\\\_(ツ)_\/¯

So I thought it was worth a try to ensure that the modal mounts in the closed state first, and then apply the open class. (See modified sandbox) And that seems to do the trick! But since it's likely a problem affecting _everyone_, I decided to try fixing it directly in `react-modal` so everyone could benefit from working transitions in Safari 14 & mobile Safari.

**Moral: When using CSS transitions, ensure that the component is rendered first before applying the class that triggers the transition. Test in Safari 14 to ensure you got it right, as other browser seem to be more lenient.**

### PR DESCRIPTION
**Pull request by benjaminpadula**
Fixes #846.

Changes proposed:
- Use `requestAnimationFrame` to delay the `after-open` class from being added until it mounts with inital CSS

Upgrade Path (for changed or removed APIs): n/a

Acceptance Checklist:
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### Additional notes:
It struck me that perhaps the issue was that when the modal is mounted, it is immediately mounted with the open state and initially renders with the after-open class. It's actually kind of surprising, then that Chrome shows a transition, when technically nothing is really changing. Perhaps the old browser interpreter is inferring developer intent or doing something wrong. ¯\\\_(ツ)_\/¯

So I thought it was worth a try to ensure that the modal mounts in the closed state first, and then apply the open class. (See modified sandbox) And that seems to do the trick! But since it's likely a problem affecting _everyone_, I decided to try fixing it directly in `react-modal` so everyone could benefit from working transitions in Safari 14 & mobile Safari.

**Moral: When using CSS transitions, ensure that the component is rendered first before applying the class that triggers the transition. Test in Safari 14 to ensure you got it right, as other/older browsers seem to be more lenient.**

### CODE REVIEW

**Review by diasbruno — APPROVED** [review]

**Comment by benjaminpadula** [comment]
Hey @diasbruno, it's been a while since I created this PR. Yes, using `requestAnimationFrame()` _improves_ the behavior here, but I have still found that it appears to skip the transition maybe 10% of the time? I have had more success locally by using `setTimeout()` with a `10-15ms` delay.

What are your thoughts on this? Would you like me to:
A) Open a new PR using the `setTimeout` approach?
B) Merge this PR as-is?
C) Solve the problem in some other way?

**Comment by diasbruno** [comment]
@benjaminpadula Can you try adding a class (with default properties like `left: 0`) to be animated. Maybe it's missing the default properties to be animated (?)

**Comment by pwfisher** [comment]
Any updates on this issue? Is there another PR to watch for a different approach to fix this? Is there any workaround in the meantime?

**Comment by diasbruno** [comment]
@pwfisher You can try @benjaminpadula's branch...It would help validate the fix.

**Comment by pwfisher** [comment]
Seems I can't, and I think it's due an error in react-modal's package.json, "main" entry.

```.lock
"react-modal@github:benjaminpadula/react-modal#fix/css-after-open-transition-in-safari-14":
  version "3.12.1"
  resolved "https://codeload.github.com/benjaminpadula/react-modal/tar.gz/848513e3057711ba53be5e60c555965426beba75"
```

```zsh
Error: Cannot find module '/Users/patrickfisher/Code/figs/syconium/node_modules/react-modal/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by diasbruno** [comment]
Use the https version:

```json
  react-modal: "https://github.com/benjaminpadula/react-modal#fix/css-after-open-transition-in-safari-14"
```

**Comment by atomanyih** [comment]
@pwfisher @diasbruno ran into a similar problem. `lib` is in the `.gitignore`, so the forked version is missing that and can't be consumed as a package. I made my own fork and committed with `lib` included: https://github.com/atomanyih/react-modal/tree/fix/css-after-open-transition-in-safari-14

There are no other changes from @benjaminpadula's branch

**Comment by diasbruno** [comment]
@atomanyih Can you make a patch to remove `lib` from the `.gitignore`, please...

**Comment by atomanyih** [comment]
@diasbruno Sure, do you want me to make a PR against the master branch of `react-modal`?

**Comment by diasbruno** [comment]
@atomanyih Yes, that would be great.

**Comment by justinledelson** [comment]
> @diasbruno Sure, do you want me to make a PR against the master branch of `react-modal`?

Any updates on the status of your branch? Will it be merged soon? Thnx

**Comment by diasbruno** [comment]
Sorry for the delay on this...I'm going to push this PR forward as it doesn't seem to cause problems.

**Comment by diasbruno** [comment]
Merged manually. See 827796d. 

Thanks, @benjaminpadula.

**Comment by justinledelson** [comment]
@diasbruno are you planning to release a new version to NPM?

**Pull request closed without merging**
