### PR TITLE
[fixed] keep references of modals when available.

### LINKED ISSUE #218: Open two modals. Hit ESC then hit ECS but nothing happens
I am using this great idea http://stackoverflow.com/questions/35623656/how-can-i-display-a-modal-dialog-in-redux-that-performs-asynchronous-actions/35641680 in order to display modals.

In order to display them, I have this code:

``` jsx
const ModalRoot = ({ list } : ModalRootPropTypes) : any => {

  if (list.size === 0) {
    return null;
  }

  return (
    <div>
      {
        list.map(({ type, props }, index) => {
          const Component = getComponent(type);

          return (
            <Component key={index} {...props} />
          );
        })
      }
    </div>
  );
};

```

The `getComponent` is like this: 

``` jsx
const DeleteArticle = (
 <Modal>
...
</Modal>
);

const MODAL_DELETE_ARTICLE = "MODAL_DELETE_ARTICLE";

const getComponent = (type : ModalActionType) : any => {
  switch (type) {

  case MODAL_DELETE_ARTICLE:
    return DeleteArticle;
....
```

So, essentially, for 2 modals, these pieces of code generates this view:

image

The HTML code is:

image

Which is very good, correct and right. But:

Now, when I hit `ESC`, the second modal hides (which is good). Then, if I press again ESC, **nothing happens**. That's because the `Modal 1` is not logger focused. 

If I click on it and hit `ECS` it is closed.

My question is:

Can I somehow focus the next modal when one is closed? (Focus `Modal 1` when `Modal 2` is closed)

### PR DESCRIPTION
**Pull request by diasbruno**
keeping a reference of all modals in order to manage
when to add/remove classes and aria from elements
correctly.

solution based on @MarkMurphy's idea #308, but it uses a simple list
to work on IE (don't really support `Set`).

Fixes #218 #231 #308.

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by ajfuller** [comment]
Hi @diasbruno, I've taken your tests from this PR and proposed an alternative solution here: https://github.com/reactjs/react-modal/pull/328

Please let me know if you have any questions or if I'm missing a case we should be testing for 😸

**Comment by diasbruno** [comment]
@ajfuller awesome. I'll check it.

**Comment by boonier** [comment]
@diasbruno thanks for the heads up on this. Any idea when this update might land?

**Comment by ChenRoth** [comment]
can you resolve the branch conflict and submit this?

**Comment by diasbruno** [comment]
@ChenRoth this needs to be ported to `v1`. I'll do it.

**Comment by boonier** [comment]
@diasbruno this hasn't been released yet has it?

**Comment by diasbruno** [comment]
@boonier I'll try to write the backport to `v1` today.

**Comment by diasbruno** [comment]
@boonier PR is #358. Please, if you have time, review the PR.

**Pull request closed without merging**
