### PR TITLE
adding a lint task that uses the rackt eslint config

### PR DESCRIPTION
**Pull request by pwmckenna**
while the style will probably change as more repos are updated (hence the overrides for this repo), this PR introduces eslint and uses the rackt eslint config). I didn't want this to change any code, so rules that did not pass were overridden/disabled to just enforce the style that already exists. 

Here is the repo for the base config being enforced: https://github.com/rackt/eslint-config-rackt

The original discussion around a centralized eslint config can be found here: https://github.com/rackt/history/pull/112

### CODE REVIEW

**Comment by diasbruno** [comment]
Hi, @pwmckenna. This is great. +1

**Comment by claydiffrient** [comment]
@pwmckenna @diasbruno I'm a bit skeptical on this one.  eslint-config-rackt doesn't seem to have been migrated over to the reactjs organization.  I'm a bit hesitant to rely on something that is npm only at the moment.

**Comment by diasbruno** [comment]
Yeah, I understand. Maybe the simple eslint would do the job.

**Comment by claydiffrient** [comment]
I'm going to go ahead and close this, opening a new issue to discuss linting in the repo.

**Pull request closed without merging**
