### PR TITLE
Added prettier and ran it where eslint runs

### PR DESCRIPTION
**Pull request by adityavohra7**
- Changed `.eslintrc` to `.eslintrc.js`because it's treated with highest priority as per [the docs](https://eslint.org/docs/user-guide/configuring#configuration-file-formats), and one can do logic in JS, etc.
- Added `prettier` to the repo via `eslint` and ran it everywhere `eslint` currently runs. Any preferences on quotes or trailing commas or JSX brackets or any [other options](https://github.com/prettier/prettier#options)? Everything is currently set to defaults.

Acceptance Checklist:

[DONE] All commits have been squashed to one.
[DONE] The commit message follows the guidelines in CONTRIBUTING.md.
[N/A] Documentation (README.md) and examples have been updated as needed.
[N/A] If this is a code change, a spec testing the functionality has been added.
[N/A] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
Look great. I'll merge those your PRs on Monday. Thank you.

**Comment by adityavohra7** [comment]
Updated the PR! Turns out the `specs` folder wasn't being linted because the run script had "spec" instead of "specs". Changed the lint script to be `eslint src/ specs/`, and ran `yarn eslint --fix` again, and manually fixed some errors.

**Comment by diasbruno** [comment]
@adityavohra7 oh, probably a typo when I did the clean up. thanks.

**Comment by adityavohra7** [comment]
Not a problem! Thanks for responding so promptly to my PR's and questions 😊

**Comment by diasbruno** [comment]
cc @adityavohra7

**Comment by diasbruno** [comment]
Merged the other PRs. This one needs to resolve the conflicts.

**Comment by adityavohra7** [comment]
@diasbruno, awesome! Thanks for merging the other PR's. I'll update this one shortly.

**Comment by adityavohra7** [comment]
@diasbruno, updated!

**Comment by diasbruno** [comment]
Thanks. Since the tests are passing, give me a heads up when it's ready.

**Comment by adityavohra7** [comment]
I'd say if tests are passing, it's OK to merge! Unless you'd like to configure `prettier` differently (single quotes, trailing commas, etc.). Though that's easily done as a followup (one line manual change in `.eslintrc.js`).

**Pull request merged**
