### PR TITLE
Update defaults.md

### PR DESCRIPTION
**Pull request by kucukkanat**
More explanatory defaults.

Fixes #[issue number].

Changes proposed:
-
-
-

Upgrade Path (for changed or removed APIs):

Acceptance Checklist:
- [ ] All commits have been squashed to one.
- [ ] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [ ] Documentation (README.md) and examples have been updated as needed.
- [ ] If this is a code change, a spec testing the functionality has been added.
- [ ] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
Hi @kucukkanat This is covered in the `Style` section. Perhaps we can shrink this.

**Comment by kucukkanat** [comment]
The page looked also very empty, but yeah sure.

**Comment by diasbruno** [comment]
Yeah, Probably It would be better to merge all the pages related to `Styles`.

**Comment by diasbruno** [comment]
@kucukkanat I'll close this in favor of merging both pages. Thank you so much for taking the time to contributing.

**Comment by kucukkanat** [comment]
Thank you for your appreciation. Wish I could do more.

**Comment by diasbruno** [comment]
@kucukkanat everyone is welcome to contribute in this repo. the challenges for many projects are  respond issue fast, avoid burnout of maintainers and collaborators and review PRs. So, please, feel free to jump in on any issue/conversation and review PRs -- when you have time!

**Pull request closed without merging**
