### PR TITLE
Improvement/remove lodash add babel

### LINKED ISSUE #238: deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
### Summary:

When installing `react-modal` with NPM, i get this warning:

```
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
```
### Steps to reproduce:

Using NodeJS 6.x:  `npm install react-modal`
### Expected behavior:

I would expect no deprecated dependencies on the latest version.

I assume you want it for a pollyfill. I think there are smaller ones out there that are not deprecated, eg: https://www.npmjs.com/package/object-assign
### Additional notes:

Looks like `lodash.assign` inflates the number of dependencies quite a bit too, it would be good to remove!

```
├─┬ react-modal@1.4.0 
│ ├── element-class@0.2.2 
│ ├── exenv@1.2.0 
│ └─┬ lodash.assign@3.2.0 
│   ├─┬ lodash._baseassign@3.2.0 
│   │ └── lodash._basecopy@3.0.1 
│   ├─┬ lodash._createassigner@3.1.1 
│   │ ├── lodash._bindcallback@3.0.1 
│   │ ├── lodash._isiterateecall@3.0.9 
│   │ └── lodash.restparam@3.6.1 
│   └─┬ lodash.keys@3.1.2 
│     ├── lodash._getnative@3.9.1 
│     ├── lodash.isarguments@3.1.0 
│     └── lodash.isarray@3.0.4
```

### PR DESCRIPTION
**Pull request by rfreitas**
Fixes #238.

Changes proposed:
- Remove lodash as a dependency due to its size
- Added babel to get things like object assign for free

Acceptance Checklist:
- [ ] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
@rfreitas this PR looks good. The only problem is that it goes a little bit out of scope. If you can extract a patch that just removes the `lodash.assign`, it would be really awesome.

**Comment by claydiffrient** [comment]
I second what @diasbruno said.  We'd happily accept the change if it's scoped properly to the small change you stated.

**Comment by rfreitas** [comment]
Sorry guys, I closed the PR because indeed this branch was following up the branch on PR #239, it wasn't intended.
So you guys are good with adding babel and removing lodash? I can create a proper PR for it then.

**Comment by claydiffrient** [comment]
@rfreitas Let's just stick with removing `lodash.assign` in the PR, we can introduce Babel later perhaps.

**Comment by rfreitas** [comment]
Updated pull request here: https://github.com/reactjs/react-modal/pull/245

**Pull request closed without merging**
