### PR TITLE
[added] add Miscellaneous section to the contributions.md file

### LINKED ISSUE #1022: Npm start related issue
### Summary:
while trying to discover and try to contribute to the project, i read the contributions.md but running npm start causes the below issue
### Steps to reproduce:

Running npm start causes this error 

```node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)```

### PR DESCRIPTION
**Pull request by YassineOmrani**
Fixes #1022 ].

Changes proposed:

- added Miscellaneous section to the contribution.md file to point out that you need nodejs version 16 to start the project 

Upgrade Path (for changed or removed APIs):

Acceptance Checklist:
- [x ] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [ ] Documentation (README.md) and examples have been updated as needed.
- [ ] If this is a code change, a spec testing the functionality has been added.
- [ ] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
Thanks, @YassineOmrani. 

It would be better to also add the expected `node version < 18` 😞.
Can you add to the package.json this restriction? 

Unfortunately, this node release breaks compatibility with existing packages.

**Comment by diasbruno** [comment]
On the stack trace, have you saw which package it broke?

**Comment by YassineOmrani** [comment]
> On the stack trace, have you saw which package broke?

loader-runner and some of webpack modules broke like createHash.js under utils and NormalModule.js

**Comment by YassineOmrani** [comment]
> Thanks, @YassineOmrani.
> 
> It would be better to also add the expected `node version < 18` 😞. Can you add to the package.json this restriction?
> 
> Unfortunately, this node release breaks compatibility with existing packages.

Thanks for your quick reply @diasbruno  i will make sure to that

**Comment by diasbruno** [comment]
Thanks. I need look those dependencies, as we can never trust node releases these days 😂.

LEGIT.

**Comment by doeg** [comment]
Hey @diasbruno, this doc change might be another good one to merge! 🙌 I ran across it when I was looking for the correct node version (with the goal of fixing some of the tests). :)

**Comment by diasbruno** [comment]
This will cause problems on projects that uses node 18+. I'll open an issue to find which library has this dependency.

**Comment by diasbruno** [comment]
Webpack 4 caching mechanism is one place where this issue happens.

 I'll try to upgrade webpack to see if it fixes for nodejs 18.

>    at module.exports (/Users/dias/Programming/react-modal/node_modules/webpack/lib/util/createHash.js:135:53)

```shell
/Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:133
		if(isError) throw e;
		            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/dias/Programming/react-modal/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/dias/Programming/react-modal/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/dias/Programming/react-modal/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/dias/Programming/react-modal/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/dias/Programming/react-modal/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at module.exports (/Users/dias/Programming/react-modal/node_modules/babel-loader/lib/index.js:182:8)
    at LOADER_EXECUTION (/Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/dias/Programming/react-modal/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/dias/Programming/react-modal/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/dias/Programming/react-modal/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/dias/Programming/react-modal/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Pull request merged**
