### PR TITLE
[chore] Added table of contents

### PR DESCRIPTION
**Pull request by andrewjmead**
Changes proposed:

- I've added table of contents to the docs.

Upgrade Path (for changed or removed APIs):

- N/A

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
@andrewjmead Can you squash all the commits and add at the beginning of the message `[chore]`? This helps to generate the changelog.

**Comment by andrewjmead** [comment]
@diasbruno done!

**Comment by diasbruno** [comment]
Awesome! I'm finishing to update the changelog then I'll merge this! Thanks.

**Comment by diasbruno** [comment]
I shouldn't have used the GitHub rebase. ¬¬
This was merged. Your commit is 4ec7184.
Thank you, @andrewjmead.

**Pull request closed without merging**
