### PR TITLE
Fix lifecycle methods usages

### LINKED ISSUE #637: Remove usages of unsafe lifecycle methods
React team recently published a blogpost: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

TL;DR: `cWM`, `cWRP`, and `cWU` methods are considered unsafe for future async rendering and will be deprecated soon. The recommended way for open source maintainers to deal with it is to use [`react-lifecycles-compat`](https://github.com/reactjs/react-lifecycles-compat) package and migrate to new `static getDerivedStateToProps` method

### PR DESCRIPTION
**Pull request by Hypnosphi**
Fixes #637 

See https://github.com/reactjs/react-modal/pull/639/files/67a74bd23915960d5421d6b9c77b6ab7a47675b4#diff-476e2e918a31cbbf34324b08ddeee24e

Acceptance Checklist:
- [ ] All commits have been squashed to one. — Why don't you just do it when merging? GitHub has a UI for that
- [ ] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [ ] Documentation (README.md) and examples have been updated as needed.
- [ ] If this is a code change, a spec testing the functionality has been added.
- [ ] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
I'll try to update the PR template. :)

**Comment by diasbruno** [comment]
@Hypnosphi can you rebase this?

**Comment by diasbruno** [comment]
This  seems ready for merge. Can I merge this, @Hypnosphi ?

**Comment by Hypnosphi** [comment]
Sure, thanks

**Comment by diasbruno** [comment]
I'll do some testing today before release the new version.

**Pull request merged**
