### PR TITLE
Adds Return key press support

### PR DESCRIPTION
**Pull request by david1asher**
Fixes #[issue number].

Changes proposed:
Adds Return key press support
-
-

Upgrade Path (for changed or removed APIs):
No changes to existing API or removals, just an addition

Acceptance Checklist:
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [ ] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by david1asher** [comment]
>If this is a code change, a spec testing the functionality has been added.
where should this be added?

**Comment by diasbruno** [comment]
Hi @david1asher, can you give a little bit of context of why the modal can be closed on pressing enter? 

If I have a form inside of the modal, and there is a button with `type=submit`, what should happen in this case?

**Comment by david1asher** [comment]
@diasbruno thank you for your replay
I was thinking of a particular scenario, when actions are being done inside the modal, and pressing the `return` key will confirm/submit the actions done.

If you don't see a point of adding this i would greatly appreciate you advising another change which is welcome and needed in this repo or another since im looking to contribute somewhere

**Comment by diasbruno** [comment]
@david1asher There are too many things that can respond to a `Enter` and sometimes it's a bit hard to combine all those. 

Well, if you know you are going to trigger a submit handler, it can also call the `onRequestClose` handler.

**Comment by david1asher** [comment]
Well unless you have a suggestion for another small first time pr(which is very welcome:)) 
ill be on my way

**Comment by diasbruno** [comment]
Thanks, @david1asher. Sometimes this happens, but it's ok. 

Any help is always welcome. When I started contributing for this project, I've tried to answer issues and implement/fix some stuff. So, that's a great place to start...don't rush to contribute and anything else I'll do my best to help.

**Pull request closed without merging**
