### PR TITLE
Update bundling scheme

### LINKED ISSUE #332: Reduce build size by swapping out lodash.assign for a minimal Object.assign
I did a clone of the repo followed by `NODE_ENV=production scripts/build`, which produced a 16826 bytes react-modal.min.js (5358 bytes gzipped).

Replacing the lodash assign import in ModalPortal.js with a minimal Object.assign polyfill (I took the TS one just for example):
```
function assign(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
}
```

...produced a 14516 bytes react-modal.min.js (4418 bytes gzipped).

That's an 18% (gzipped size) reduction, which adds up on slow networks and devices.

### PR DESCRIPTION
**Pull request by claydiffrient**
This commit sets things up to work properly when
publishing to npm.  Prior to publishing the package
items from the src/ folder will be processed with Babel
and stored in the lib/ folder. The lib/ folder will
not be present in the repository.  The src/ folder similarly
will not be available when looking at the installed package.

In addition this commit also fixes #332 by adding the
`babel-plugin-transform-object-assign` plugin and removing
`lodash.assign`

Changes proposed:
- `lib/` renamed to `src/` in repo
- `src/` transpiled through Babel to `lib` on publish
- `lodash.assign` removed, in favor of `babel-plugin-transform-object-assign`

Acceptance Checklist:
- [x] All commits have been squashed to one.
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
This is what I got with commit 96cc7ae.

```sh
ERROR in ./src/index.js
Module not found: Error: Can't resolve 'react-modal' in '/projects/react-modal-qa/src'
 @ ./src/index.js 13:18-40
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/index.js
webpack: Failed to compile.
```

**Comment by claydiffrient** [comment]
Hmm... I bet I missed something that specifically targets src/ in the transfer.  I'll have to look more into that.  There's some linting things I've got to fix up too.

**Comment by diasbruno** [comment]
Probably this `package.json`.

```json
{
  "main": "./lib/index.js"
}
```

**Comment by diasbruno** [comment]
Even after added `"babel-transform-class-properties"` it keeps failing.

```sh
Hash: ebb4dcf49212a3d0a840
Version: webpack 2.2.1
Time: 13223ms
        Asset     Size  Chunks                    Chunk Names
./app/main.js  1.04 MB       0  [emitted]  [big]  main
chunk    {0} ./app/main.js (main) 1 MB [entry] [rendered]
   [26] ./~/react/lib/React.js 2.69 kB {0} [built]
  [113] ./src/index.js 3.05 kB {0} [built]
  [114] (webpack)-dev-server/client?http://0.0.0.0:8080 5.28 kB {0} [built]
  [140] ./~/querystring-es3/index.js 127 bytes {0} [built]
  [142] ./~/react-dom/index.js 59 bytes {0} [built]
  [214] ./~/react-modal/src/components/Modal.js 386 bytes {0} [built] [failed] [1 error]
  [215] ./~/react-modal/src/index.js 63 bytes {0} [built]
  [227] ./~/react/react.js 56 bytes {0} [built]
  [255] ./~/strip-ansi/index.js 161 bytes {0} [built]
  [257] ./~/url/url.js 23.3 kB {0} [built]
  [258] ./~/url/util.js 314 bytes {0} [built]
  [259] (webpack)-dev-server/client/overlay.js 3.6 kB {0} [built]
  [260] (webpack)-dev-server/client/socket.js 856 bytes {0} [built]
  [262] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [263] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/index.js 40 bytes {0} [built]
     + 249 hidden modules

ERROR in ./~/react-modal/src/components/Modal.js
Module parse failed: /projects/react-modal-qa/node_modules/react-modal/src/components/Modal.js Unexpected token (19:19)
You may need an appropriate loader to handle this file type.
|
|   /* eslint-disable react/no-unused-prop-types */
|   static propTypes ({=} THIS})  {
|     isOpen: React.PropTypes.bool.isRequired,
|     style: React.PropTypes.shape({
 @ ./~/react-modal/src/index.js 1:0-39
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/index.js
webpack: Failed to compile.
```

**Comment by claydiffrient** [comment]
Cool cool, I'm busy at the moment but I'll do a bit more this evening.

**Comment by diasbruno** [comment]
I'll revert this changes and continue in another branch.

**Comment by claydiffrient** [comment]
I'm not sure where the issues are coming from @diasbruno.  I set up a local testing repository and linked in my `react-modal` via `yarn link` and `yarn link react-modal` and things seem to work fine.

Oh I think I know why.  In your react-modal-qa repo you are referencing the branch directly, but I believe that will not run the pre-publish hook to compile the code beforehand.  So it'll never see the `lib/` directory that gets created prior to publish.  Would you mind trying it out using `yarn/npm link` and see if it works as you would expect?

**Comment by diasbruno** [comment]
I'll check it.

**Comment by diasbruno** [comment]
Yep, that was the problem. Using `npm link` really executes the prepublish command.

**Pull request merged**
