### PR TITLE
Avoid stopPropagation

### PR DESCRIPTION
**Pull request by ct-dali**
This PR addresses issue #115.

https://css-tricks.com/dangers-stopping-event-propagation/

### CODE REVIEW

**Comment by ct-dali** [comment]
@ryanflorence @mzabriskie is this package being maintained??

**Comment by claydiffrient** [comment]
@ct-dali The package is being maintained.  Sorry for the delay in getting to this.  If you could squash these commits together and include a spec testing that this fixes the problem, I'd be happy to merge it.

**Comment by ct-dali** [comment]
@claydiffrient I updated the PR, please review and merge.

**Comment by claydiffrient** [comment]
@ct-dali Looks good, if you would squash the commits I'm happy to merge it.

**Comment by ct-dali** [comment]
GitHub has a new "squash commits and merge" feature: https://github.com/blog/2141-squash-your-commits

**Pull request merged**
