### PR TITLE
[fixed] Allow empty classNames for body

### PR DESCRIPTION
**Pull request by jitinmaher**
Fixes [#[664]](https://github.com/reactjs/react-modal/issues/664) and [ #[721]](https://github.com/reactjs/react-modal/issues/721).

 [#[664]](https://github.com/reactjs/react-modal/issues/664): This PR allows empty classNames for body and portal when `bodyOpenClassName ` is set with no value( `null or ""`  )

[ #[721]](https://github.com/reactjs/react-modal/issues/721): The PR also regenerates package-lock.json which fixes event-stream-3.3.6 issue caused because of the [recent security incident ](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)

Acceptance Checklist:
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
@jitinmaher Thanks for working on this. 
Yep, that seems to be the case. 
The only thing missing is to update the documentation and, once we have the tests passing, we can merge this PR.

**Comment by jitinmaher** [comment]
Thanks for the review @diasbruno . I have updated the documentation.

**Comment by jitinmaher** [comment]
@diasbruno Updated docs/README.md 👍

**Comment by jitinmaher** [comment]
@diasbruno docs/README.md has been Updated  👍

**Comment by jitinmaher** [comment]
@diasbruno Updated the lock file to fix the event-stream issue. Builds and test cases are passing 👍.

**Comment by diasbruno** [comment]
Good job, @jitinmaher! I'll finish the review later and merge this. Probably, I'll release a new version tomorrow.

**Comment by jitinmaher** [comment]
Thanks @diasbruno . Looking forward for the new version!!

**Comment by jitinmaher** [comment]
Hey @diasbruno , any updates on the merge?

**Comment by jitinmaher** [comment]
Ping @diasbruno 

Sorry to bother you again. Any update on the merge?

**Comment by diasbruno** [comment]
No problem, @jitinmaher...actually, thanks for remind me to do it.

**Comment by diasbruno** [comment]
@jitinmaher thanks you for having a look on this issue and for your patience to merge this. Good job!

**Comment by jitinmaher** [comment]
@diasbruno Thank you so much for the merge 👍

**Comment by diasbruno** [comment]
Released version 3.7.1.

**Comment by jitinmaher** [comment]
Thanks for the version update @diasbruno  🙂

**Pull request merged**
