### PR TITLE
Update on_request_close.md

### PR DESCRIPTION
**Pull request by kucukkanat**
shouldCloseOnOverlayClick note added.

Fixes #[issue number].

Changes proposed:
-
-
-

Upgrade Path (for changed or removed APIs):

Acceptance Checklist:
- [ ] All commits have been squashed to one.
- [ ] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [ ] Documentation (README.md) and examples have been updated as needed.
- [ ] If this is a code change, a spec testing the functionality has been added.
- [ ] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
@kucukkanat We can make this message more concise like `To close the modal by clicking on the overlay, it will depend on the `onRequestClose`....

**Comment by diasbruno** [comment]
On a second look, this actually looks good. 

@kucukkanat Give me a heads up if this one is ready to be merged.

**Comment by kucukkanat** [comment]
Yess🤘🏻👍🏻

**Comment by diasbruno** [comment]
Merged! Thank you!

**Comment by diasbruno** [comment]
Published the updates.

**Pull request merged**
