### PR TITLE
Support React 18

### LINKED ISSUE #937: React 18 Support
### Steps to reproduce:

 1.
 2.
 3.

### Expected behavior:

It would be nice to add React v18 to `peerDependencies` to mak using this library easier in a React 18 app.

### PR DESCRIPTION
**Pull request by swissspidy**
Fixes #937.

Changes proposed:

- Support `react` and `react-dom` v18 as peer dependency
-

Upgrade Path (for changed or removed APIs):

Acceptance Checklist:
- [x] The commit message follows the guidelines in `CONTRIBUTING.md`.
- [x] Documentation (README.md) and examples have been updated as needed.
- [x] If this is a code change, a spec testing the functionality has been added.
- [x] If the commit message has [changed] or [removed], there is an upgrade path above.

### CODE REVIEW

**Comment by diasbruno** [comment]
I'll merge #938 because it's older.

**Comment by swissspidy** [comment]
Thanks! No idea how I missed that one 🤦 

Appreciate the quick feedback!

**Comment by VeRJiL** [comment]
still does not work for react v18 using npm

```
$ npm i react-modal
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: react@18.0.0
npm ERR! node_modules/react
npm ERR!   react@"18.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16 || ^17" from react-modal@3.14.4
npm ERR! node_modules/react-modal
npm ERR!   react-modal@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

```

**Comment by ebrahimiaval** [comment]
I fix this with `npm i --force`  but please update faster!

**Comment by swissspidy** [comment]
@diasbruno FYI, it looks like v3.15.1 was tagged but not published to npm

**Comment by kkowalczuk** [comment]
@swissspidy should we reopen https://github.com/reactjs/react-modal/issues/937 for better visibility? I [have mentioned that already](https://github.com/reactjs/react-modal/issues/937#issuecomment-1098738220) last week.

**Comment by diasbruno** [comment]
Hi. I had a little problem with my mac and I'm kinda locked out from npm. Hope to get this done at least by the weekend.

**Pull request closed without merging**
